import { CartDrawer } from "@/components/CartDrawer";
import { StoreHeader } from "@/components/StoreHeader";
import { StoreFooter } from "@/components/StoreFooter";
import { trpc } from "@/lib/trpc";
import { Mail, MessageCircle } from "lucide-react";
import { FormEvent, useState } from "react";

export default function Contact() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [subject, setSubject] = useState(""); const [message, setMessage] = useState(""); const [website, setWebsite] = useState(""); const [notice, setNotice] = useState("");
  const send = trpc.storefront.contact.submit.useMutation({ onSuccess: () => { setNotice("Your message reached Ehode. Thank you for getting in touch."); setSubject(""); setMessage(""); } });
  async function submit(event: FormEvent) { event.preventDefault(); setNotice(""); try { await send.mutateAsync({ name, email, subject, message, website }); } catch { setNotice("Your message could not be sent right now. Please try again shortly."); } }
  return <div className="store-page buyer-page"><StoreHeader/><main className="contact-shell"><section className="contact-intro"><div><p className="buyer-kicker">Contact Ehode</p><h1>Let’s make room for your question.</h1><p>Ask about a digital resource, a purchase, a download problem, or an idea you would like to see in the shop.</p></div><div className="contact-intro__icon"><MessageCircle size={38}/><span>Your message is sent privately to the Ehode owner. Replies go to the email you enter.</span></div></section><section className="contact-support"><h2>How can we help?</h2><div><p><strong>Order or download help:</strong> include the email used for the order, product name, and a short description of the issue.</p><p><strong>Before buying:</strong> ask about file formats, product details, or licence information before checkout.</p><p><strong>Privacy:</strong> do not include payment-card details or other sensitive information in this form.</p></div></section><section className="contact-card"><form className="buyer-form" onSubmit={submit}><div className="contact-grid"><label>Name<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} maxLength={120} required/></label><label>Email<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" required/></label></div><label>Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} minLength={3} maxLength={180} required/></label><label>Message<textarea value={message} onChange={(event) => setMessage(event.target.value)} minLength={10} maxLength={6000} required/></label><label className="contact-trap" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={(event) => setWebsite(event.target.value)}/></label>{notice ? <p className="buyer-notice buyer-notice--success">{notice}</p> : null}<button className="buyer-primary" disabled={send.isPending}>{send.isPending ? "Sending…" : <><Mail size={16}/> Send private message</>}</button></form></section></main><StoreFooter/><CartDrawer/></div>;
}
